services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: app
    image: shuiwujiao/AI-Codereview-Gitlab/ai-codereview-gitlab:1.0.0
    ports:
      - "5001:5001"
      - "5002:5002"
    volumes:
      - ./data:/app/data
      - ./log:/app/log
    env_file:
      - ./conf/.env
    restart: unless-stopped
